apiVersion: debezium.io/v1alpha1
kind: DebeziumServer
metadata:
  name: dbz-postgres
spec:
  image: debezium/server:2.7
  quarkus:
    config:
      log.console.json: false
      kubernetes-config.enabled: true
      kubernetes-config.secrets: postgres-secret
  sink:
    type: pulsar
    config:
      client.serviceUrl: "pulsar://pulsar-proxy.default.svc.cluster.local:6650"
  source:
    class: io.debezium.connector.postgresql.PostgresConnector
    config:
      database.hostname: postgres-cluster-rw
      database.port: 5432
      database.user: postgres
      database.password: password
      database.dbname: appdb
      topic.prefix: appdb
      schema.include.list: public
      plugin.name: pgoutput
