apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: pulsar
spec:
  adminServiceSecureURL: https://pulsar-proxy.default.svc.cluster.local:8443
  brokerServiceSecureURL: pulsar+ssl://pulsar-proxy.default.svc.cluster.local:6651
  clusterName: pulsar
  authentication:
    token:
      secretRef:
        name: token-superuser
        key: superuser.jwt
