apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: pulsar
spec:
  adminServiceURL: http://pulsar-proxy.default.svc.cluster.local:8080
  brokerServiceURL: pulsar://pulsar-proxy.default.svc.cluster.local:6650
  clusterName: pulsar
